TravelOKViajes/Controllers/EncuestaController.cs
using CapaDatos;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelOKViajes.Controllers
{
    public class EncuestaController : Controller
    {
        // GET: Encuesta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult InicialEncuesta()
        {
            var resultado = new JObject();
            try
            {
                CD_Destinos cdDestino = new CD_Destinos();
                List<TO_Destino> lsDestinos = new List<TO_Destino>();
                CD_Encuesta cdEncuesta = new CD_Encuesta();
                List<TO_Encuesta> lsEncuesta = new List<TO_Encuesta>();
                lsEncuesta = cdEncuesta.fnlsObtienePreguntas();
                lsDestinos = cdDestino.lsObtieneDestinos();
                if (lsDestinos.Count > 0)
                {
                    JToken arDestinos = new JArray(from d in lsDestinos
                                                   select new JObject(
                                                      new JProperty("Viaje", d.IdViaje),
                                                      new JProperty("Destino", d.Destino)
                                                    ));
                    resultado["LsDestinos"] = arDestinos;
                    resultado["LsEncuesta"] = new JArray(from p in lsEncuesta
                                                         select new JObject(
                                                             new JProperty("IdPregunta", p.IdPregunta),
                                                             new JProperty("nvPregunta", p.nvPregunta),
                                                             new JProperty("iTipoPreg", p.iTipoPreg)
                                                         ));
                    resultado["Exito"] = true;
                }
            }
            catch (Exception x)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        // POST: Encuesta/Create
        [HttpPost]
        public ActionResult RecibeEncuesta(List<TO_EncuestaResp> SalidaRes)
        {
            var resultado = new JObject();
            try
            {
                CD_Encuesta cdEncuesta = new CD_Encuesta();
                if (cdEncuesta.fnbInsertaEncuesta(SalidaRes))
                {
                    resultado["Exito"] = true;
                }
                else
                {
                    resultado["Exito"] = false;
                }
            }
            catch(Exception ex)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }
    }
}

TravelOKViajes/Controllers/PerfilController.cs
using CapaDatos;
using CapaModelo;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace TravelOKViajes.Controllers
{
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult Index()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            return View();
        }

        [HttpGet]
        public ActionResult InicialPerfil()
        {
            string sUsuario = Session["UserID"].ToString();

            var resultado = new JObject();
            try
            {
                CD_Perfil cdPerfil = new CD_Perfil();
                List<cmDeudaViajeros> olsDeudaViaje = new List<cmDeudaViajeros>();
                olsDeudaViaje = cdPerfil.fnlsRecuperaInfo(sUsuario);
                if (olsDeudaViaje.Count > 0)
                {
                    resultado["olsDeudaViaje"] = JToken.FromObject(olsDeudaViaje);
                    resultado["Exito"] = true;
                }
                else
                {
                    resultado["Exito"] = false;
                    resultado["NoViaje"] = true;
                }
            }
            catch (Exception x)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        [HttpPost]
        public ActionResult InsertaPago(cmInsertaPago DatosPago)
        {
            var resultado = new JObject();
            try
            {
                if(DatosPago.sNomArch== "undefined")
                {
                    resultado["Exito"] = false;
                    resultado["Mensaje"] = "No ha seleccionado ningún archivo";
                    return Content(resultado.ToString());
                }
                DatosPago.idUsuario = Session["UserID"].ToString();
                foreach (string _fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[_fileName];
                    DatosPago.sNomArch = file.FileName;
                    if (file.ContentType != "image/png" && file.ContentType != "image/jpeg")
                    {
                        resultado["Exito"] = false;
                        resultado["Mensaje"] = "El archivo debe ser formato PDF";
                        return Content(resultado.ToString());
                    }
                    MemoryStream target = new MemoryStream();
                    file.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();
                    DatosPago.Archivo = data;
                };
                CD_Perfil ocdPerf = new CD_Perfil();
                if (ocdPerf.fnbActualizaPago(DatosPago))
                    resultado["Exito"] = true;
                else
                {
                    resultado["Exito"] = false;
                    resultado["Mensaje"] = "No se pudo realizar la actualización correctamente.";
                }
                return Content(resultado.ToString());
            }
            catch (Exception ex)
            {
                resultado["Exito"] = false;
                resultado["Mensaje"] = ex.Message.ToString();
                return Content(resultado.ToString());
            }
        }
    }
}

TravelOKViajes/Controllers/VentaController.cs
using CapaDatos;
using CapaModelo;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MercadoPago;
using MercadoPago.Resources;
using MercadoPago.DataStructures.Preference;
using MercadoPago.Common;
using TravelOKViajes.General;

namespace TravelOKViajes.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta
        

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InicialVenta(cmVentaDet detVenta)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            /*return View();*/
            /*return RedirectToAction("SeleccionVenta");*/
            var resultado = new JObject();
            CD_Transporte cdTran = new CD_Transporte();
            cmTransporte oTran = cdTran.fnoObtieneTransporte(detVenta);
            if (oTran != null)
            {
                resultado["lsOcupados"] = JToken.FromObject(cdTran.fnlsObtieneOcupados(detVenta.idVenta));
                resultado["oTransporte"] = JToken.FromObject(oTran);
                resultado["Exito"] = true;
            }
            else
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        public ActionResult DetalleVenta()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            else
            {                
                return View();
            }
        }
        public ActionResult SeleccionVenta()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            else
            {
                return View();
            }
        }

        public ActionResult InicioSelecVenta()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            var resultado = new JObject();
            try
            {
                CD_SelecVen cdSelVen = new CD_SelecVen();
                List<cmCostos> lsDetDes = new List<cmCostos>();
                lsDetDes = cdSelVen.fnlsObtieneDestinosDet();
                if (lsDetDes.Count > 0)
                {
                    resultado["LsDestinos"] = JToken.FromObject(lsDetDes);
                    resultado["Exito"] = true;
                }
            }
            catch (Exception x)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        public ActionResult InicioDetVenta(cmVentaDet oDest)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            var resultado = new JObject();
            try
            {
                CD_DetVenta odVenta = new CD_DetVenta();
                List<cmVentaDet> lsDetSal = new List<cmVentaDet>();
                lsDetSal = odVenta.fnlsRecuperaSalidaDes(oDest);
                
                if (lsDetSal.Count > 0)
                {
                    resultado["LsSalidas"] = JToken.FromObject(lsDetSal);
                    resultado["Exito"] = true;
                }
            }
            catch (Exception x)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        [HttpPost]
        public ActionResult ObtienePropuestas(cmHabitacion oHabitacion)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            var resultado = new JObject();
            try
            {
                CD_DetVenta odVenta = new CD_DetVenta();
                List<cmHabitacion> lsHabitaciones = new List<cmHabitacion>();
                int count = 0;
                if (oHabitacion.iPasajeros > 2)
                {
                    while (count < 3)
                    {
                        oHabitacion.iDecremento = count;
                        lsHabitaciones = odVenta.fnlsRecuperaOpciones(oHabitacion);
                        decimal tot = 0;
                        foreach(cmHabitacion hab in lsHabitaciones)
                        {
                            tot += hab.dCosto;
                        }
                        if (count == 0)
                        {
                            resultado["Opcion0"] = JToken.FromObject(lsHabitaciones);
                            resultado["Total0"] = tot;
                        }
                        if (count == 1)
                        {
                            resultado["Opcion1"] = JToken.FromObject(lsHabitaciones);
                            resultado["Total1"] = tot;
                        }
                        if (count == 2)
                        {
                            resultado["Opcion2"] = JToken.FromObject(lsHabitaciones);
                            resultado["Total2"] = tot;
                        }
                        count++;
                    }
                }
                else
                {
                    oHabitacion.iDecremento = 0;
                    lsHabitaciones = odVenta.fnlsRecuperaOpciones(oHabitacion);
                    decimal tot = 0;
                    foreach (cmHabitacion hab in lsHabitaciones)
                    {
                        tot += hab.dCosto;
                    }
                    resultado["Opcion"] = JToken.FromObject(lsHabitaciones);
                    resultado["Total"] = tot;
                }
                if (lsHabitaciones.Count > 0)
                {
                    resultado["Exito"] = true;
                }

                /*lsHabitaciones = odVenta.fnlsRecuperaOpciones(new cmHabitacion
                {
                    iPasajeros = 10,
                    idViaje = 2,
                    iDecremento = 0
                });*/

            }
            catch(Exception ex)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());
        }

        [HttpPost]
        public ActionResult RecuperaFechasVen(cmVentaDet detVenta)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            var resultado = new JObject();
            try
            {
                CD_Viajes cdViaje = new CD_Viajes();
                List<cmVentaDet> lsVentaDetFec = new List<cmVentaDet>();
                lsVentaDetFec = cdViaje.fnlsRecuperaFechaVen(detVenta);

                if (lsVentaDetFec.Count > 0)
                {
                    JToken arFecDest = new JArray(from d in lsVentaDetFec
                                                  select new JObject(
                                                     new JProperty("IdVenta", d.idVenta),
                                                     new JProperty("dtFecha", d.dtFecha)
                                                   ));
                    resultado["LsFechaVta"] = arFecDest;
                    resultado["Exito"] = true;
                }
            }
            catch (Exception x)
            {
                resultado["Exito"] = false;
            }
            return Content(resultado.ToString());

        }

        public ActionResult RegistraUsuarios()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            return View();
        }
        [HttpPost]
        public ActionResult InsertaViajeros(List<cmViajeros> oUsrViajeros)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("TravelInicio", "Logueo");
            }
            JObject resultado = new JObject();
            if (oUsrViajeros.Count > 0)
            {
                CD_Viajeros cdViajeros = new CD_Viajeros();
                oUsrViajeros.ToList().ForEach(cc => cc.idUsuario = Session["UserID"].ToString());
                cmHabitacion oHabitacion = new cmHabitacion
                {
                    iPasajeros = oUsrViajeros.Count,
                    idViaje = oUsrViajeros[0].idViaje
                };
                CD_DetVenta odVenta = new CD_DetVenta();
                decimal tot = 0;                
                switch (oUsrViajeros[0].sOpcionTour)
                {
                    case "btnOp-0":
                        oHabitacion.iDecremento = 0;
                        foreach (cmHabitacion hab in odVenta.fnlsRecuperaOpciones(oHabitacion))
                        {
                            tot += hab.dCosto;
                        }
                        oUsrViajeros.ToList().ForEach(cc => cc.dCostoTotal = tot);
                        break;
                    case "btnOp-1":
                        oHabitacion.iDecremento = 1;
                        foreach (cmHabitacion hab in odVenta.fnlsRecuperaOpciones(oHabitacion))
                        {
                            tot += hab.dCosto;
                        }
                        oUsrViajeros.ToList().ForEach(cc => cc.dCostoTotal = tot);
                        break;
                    case "btnOp-2":
                        oHabitacion.iDecremento = 2;
                        foreach (cmHabitacion hab in odVenta.fnlsRecuperaOpciones(oHabitacion))
                        {
                            tot += hab.dCosto;
                        }

TravelOKViajes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - TravelOK</title>
    <script src="~/Scripts/Project/jQuery/jquery-3.4.1.js"></script>
    <link href="~/Content/Project/Bootstrap/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/Content/Project/Bootstrap/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/Content/Project/Bootstrap/bootstrap.css" rel="stylesheet" />

    <link href="~/Content/Project/cssGeneral.css" rel="stylesheet" />
    <script src="~/Scripts/Project/Bootstrap/bootstrap.bundle.js"></script>
    <script src="~/Scripts/Project/Bootstrap/bootstrap.js"></script>
    <script src="~/Scripts/Project/list.min.js"></script>
    <script src="~/Scripts/Project/sweetalert2.all.min.js"></script>
    <script src="~/Scripts/Project/jsMensajes.js"></script>
    <script src="~/Scripts/Project/jsGeneral.js"></script>
</head>
<body>
    <div id="dvCarga">
        <div class="loader"></div>
    </div>    
    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <!--@Html.ActionLink("Confirma", "ConfirmaVenta", "Venta", null, null)-->
                @Html.ActionLink("DESTINOS", "Destinos", "Home", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
                @Html.ActionLink("VIAJEROS", "Comunidad", "Home", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
                @if (Session["UserName"] != null)
                {
                    @Html.ActionLink("Bienvenido "+ @Session["UserName"].ToString(), "Index", "Perfil", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
                }
                else
                {
                    @Html.ActionLink("Iniciar sesión", "TravelInicio", "Logueo", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
                    @Html.ActionLink("Registrarse", "TravelRegistro", "Logueo", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
                }
                @Html.ActionLink("¡Evalúa tu viaje!", "Index", "Encuesta", new { @class = "nav-item nav-link" }, new { @class = "nav-item nav-link" })
            </div>
        </div>
    </nav>

    <div id="dvBarra">
        <ul class="ulnav">
            <li id="liInd" class="nav-item active">
                <a class="nav-link linini" href='@Url.Action("Index", "Home")'>
                </a>
            </li>
            <li id="liIcons">
                <ul id="ulIcons">
                    <li>
                        <a id="awp" target="_blank" href="https://wa.me/5212223602031"></a>
                    </li>
                    <li>
                        <a id="afb" target="_blank" href="https://www.facebook.com/Traveelok/?ref=bookmarks"></a>
                    </li>
                    <li>
                        <a id="aig" target="_blank" href="https://www.instagram.com/travelokmx/"></a>
                    </li>
                </ul>
            </li>
        </ul>

    </div>
    <div id="carouselExampleControls" class="carousel car1 slide d-flex justify-content-center" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="carh d-block w-100" src="~/Img/CarruselPrincipal/1.jpg" id="Fsl" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="carh d-block w-100" src="~/Img/CarruselPrincipal/2.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="carh d-block w-100" src="~/Img/CarruselPrincipal/3.jpg" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="carh d-block w-100" src="~/Img/CarruselPrincipal/4.jpg" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="carh d-block w-100" src="~/Img/CarruselPrincipal/5.jpg" alt="Third slide">
            </div>
        </div>
    </div>
    <div class="container body-content col-12">
        @RenderBody()
        <p id="pclear"></p>
        <hr />

    </div>

    <!--Carrusel Dinamico-->
    <div class="modal fade col-12" id="modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modalDialog" role="document">
            <div class="modal-content modalContent">
                <div class="modal-header modal-header-success">
                    <h5 class="modal-title" id="exampleModalLabel">Vive una experiencia Travel</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">x</button>
                </div>
                <div class="modal-body">
                    <div class="container col-12">
                        <div class="car col-6">
                            <div id="carouselExampleIndicators" class="carousel slide h-100" data-ride="carousel">
                                <ol class="carousel-indicators"></ol>
                                <div class="carousel-inner">
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                        <div class="dvText col-6 h-100">
                            <div class="m-auto">
                                <h1 class="mb-1 mt-5 hTitmodal"></h1>
                                <h2 class="mb-2 hSubTmodal"></h2>
                                <div id="dvInfo" class="mb-2">
                                </div>
                                <div class="col-12 d-flex justify-content-around mb-2">
                                    <div class="btn text-white">Itinerario</div>
                                    <div class="btn text-white">Guia de Viaje</div>
                                    <div class="btn text-white">Recomendaciones</div>
                                    <div class="btn text-white">RESERVA AHORA</div>
                                </div>
                                <div id="dvBarBaja" class="d-flex justify-content-around col-12">
                                    <div class="col-6">
                                        <div id="dvAnu1">
                                            ¿QUIÉRES REALIZAR EL VIAJE DE TUS SUEÑOS?
                                        </div>
                                        <div id="dvAnu2">
                                            Envíanos un mensaje y un asesor resolverá !TODAS TUS DUDAS¡
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div id="wbtn">
                                            Mándanos un whatsapp
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!--Fin Carrusel Dinamico-->

    <footer class="col-12;">
        <ul id="ulFooter" class="col-12">
            <li id="liQui" class="nav-item">
                <img class="iconitem" src="~/Img/iconos/pe.png" />@Html.ActionLink("¿Quiénes somos?", "QuienesSomos", "Home")
            </li>
            <li id="liCon" class="nav-item">
                @Html.ActionLink("Contacto", "Contact", "Home")
                <img class="iconitem" src="~/Img/iconos/tel.png" />
                <img class="iconitem" src="~/Img/iconos/ma.png" />
                <img class="iconitem" src="~/Img/iconos/ub.png" />
            </li>
            <li id="liBlo" class="nav-item">
                @Html.ActionLink("Blog", "Blog", "Home")
            </li>
            <!--<li id="liAviso" class="nav-item">
                    @Html.ActionLink("Aviso de privacidad", "Blog", "Home")
                </li>
        -->
            <li id="liTer" class="nav-item">
                @Html.ActionLink("Términos y condiciones", "Terminos", "Home")
            </li>
        </ul>
        <input type="hidden" id="urlInicioBlog" value="@Url.Action("obtenerPublicaciones","Home")" />
        <input type="hidden" id="urlDetallePublicacion" value="@Url.Action("obtenerDetallePublicacion","Home")" />
    </footer>
    <script src="~/Scripts/Project/jsLayout.js"></script>
</body>
</html>