TravelOkAdmin/Controllers/DestinosController.cs
using CapaDatos;
using CapaDatos.Administrador;
using CapaModelo;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelOkAdmin.Controllers
{
    public class DestinosController : Controller
    {
        // GET: Destinos
        public ActionResult Index()
        {
            //if (Session["Usuario"] != null)
                return View();
            /*else
                return RedirectToAction("Index", "Login");*/
        }

        public ActionResult Carrusel()
        {
            return View();
        }

        public ActionResult InicialDestinos()
        {
            var resultado = new JObject();
            CD_Destinos cdDestino = new CD_Destinos();
            List<TO_Destino> lsDestinos = new List<TO_Destino>();
            lsDestinos = cdDestino.lsObtieneDestinos();
            if (lsDestinos.Count > 0)
            {
                JToken arDestinos = new JArray(from d in lsDestinos
                                               select new JObject(
                                                  new JProperty("Viaje", d.IdViaje),
                                                  new JProperty("Destino", d.Destino)
                                                ));
                resultado["LsDestinos"] = arDestinos;
                resultado["Exito"] = true;
            }
            return Content(resultado.ToString());
        }
        public ActionResult InsertaDestino(cmDestinos CDestino)
        {
            var resultado = new JObject();
            CDA_Destinos cdaDestinos = new CDA_Destinos();
            if (cdaDestinos.bInsertaDestino(CDestino))
                resultado["Exito"] = true;
            else
                resultado["Exito"] = false;
            return Content(resultado.ToString());
        }


        public ActionResult EliminaDestinoId(int idDestino)
        {
            var resultado = new JObject();
            CDA_Destinos cdaDestino = new CDA_Destinos();
            if (cdaDestino.bEliminaDestino_Id(idDestino))
            {
                resultado["Exito"] = true;
            }
            else
            {
                resultado["Exito"] = false;
            }
            //resultado["Exito"] = cdaSalida.bEliminaSalidaId(idSalida) ? true : false;
            return Content(resultado.ToString());
        }

        public ActionResult InsertaDetalleDestino(cmCarruselDestino CDetDestino)
        {
            var resultado = new JObject();
            CDA_CarruselDestino cdaDetDestinos = new CDA_CarruselDestino();
            if (cdaDetDestinos.bInsertaCarruselDestino(CDetDestino))
                resultado["Exito"] = true;
            else
                resultado["Exito"] = false;
            return Content(resultado.ToString());
        }

        // GET: Destinos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Destinos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Destinos/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Destinos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Destinos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Destinos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Destinos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelOkAdmin/Views/Destinos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Destinos
                </button>
            </h5>
        </div>
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                <h2>Inserción destino</h2>
                <form class="form-group">
                    <div id="dinDestino">Destino</div>
                    <input type="text" id="inDestino" class="form-control" placeholder="Escribe nuestro destino." />
                    <div id="dinTitulo">Título</div>
                    <input type="text" id="inTitulo" class="form-control" placeholder="Escribe el titulo." />
                    <div id="dinSubtitulo">Subtítulo</div>
                    <input type="text" id="inSubtitulo" class="form-control" placeholder="Escribe el subtítulo." />
                    <div id="dinDescripcion">Descripción</div>
                    <input type="text" id="inDescripcion" class="form-control" placeholder="Escribe la descripcion." />
                    <div id="dinGuia">Liga de la guía</div>
                    <input type="text" id="inGuia" class="form-control" placeholder="Liga de la guía." />
                    <div id="dinItin">Liga del itinerario</div>
                    <input type="text" id="inItin" class="form-control" placeholder="Liga del itinerario." />
                    <div id="dinRecom">Liga de las recomendaciones</div>
                    <input type="text" id="inRecom" class="form-control" placeholder="Liga de las recomendaciones." />
                    <div id="dvPantalla" class="dvTexto">¿Mostrar en pantalla principal?</div>
                    <label class="switch">
                        <input type="checkbox" id="chActivo">
                        <span class="slider round"></span>
                    </label>
                    <div class="clr"></div>
                    <div id="btnInsertaDestino" class="btn btn-primary">Inserta Destino</div>
                </form>
                <h2>Eliminar destino</h2>

                <form class="form-group">
                    <select class="form-control" id="selDestinos">
                        <option value="0">Selecciona el destino a eliminar</option>
                    </select>
                    <div id="btnEliminaDestino" class="btn btn-primary">Eliminar Destino</div>
                </form>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Carrusel
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                <h2>Carrusel</h2>
                <form class="form-group">

                    <div id="disDDestino">Selecciona el destino</div>

                    <select class="form-control" id="selDestinos2">
                        <option value="0">Selecciona el destino</option>
                    </select>

                    <div id="idsFoto">Nombre de la foto</div>
                    <input type="text" id="inFotoDetDestino" class="form-control" placeholder="Escribe nombre de la foto." />
                    <div id="dsDescrip">Descripción</div>
                    <input type="text" id="inDescDetDestino" class="form-control" placeholder="Escribe descripción de la foto." />
                    <div id="dvPantallaDetDest" class="dvTexto">¿Mostrar en pantalla la foto?</div>
                    <label class="switch">
                        <input type="checkbox" id="chActivoDetDest">
                        <span class="slider round"></span>
                    </label>
                    <div class="clr"></div>
                    <div id="btnInsertaDetDestino" class="btn btn-primary">Inserta DetalleDestino</div>
                    @*<div id="btnInsertaDetDestino" class="btn btn-primary">Inserta DetalleDestino</div>*@
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Project/jsDestino.js"></script>
<link href="~/Content/Project/cssDestino.css" rel="stylesheet" />
<input type="hidden" id="urlDestinoInicial" value="@Url.Action("InicialDestinos","Destinos")" />
<input type="hidden" id="urlDestinoInserta" value="@Url.Action("InsertaDestino","Destinos")" />
<input type="hidden" id="urlDestinoElimina" value="@Url.Action("EliminaDestino","Destinos")" />
<input type="hidden" id="urlDetalleDestinoInserta" value="@Url.Action("InsertaDetalleDestino","Destinos")" />